repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --select=E,F,I,N
          - --ignore=E203,E501
          - --per-file-ignores=__init__.py:F401

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: local
    hooks:
      - id: check-todo
        name: Check for TODO comments
        entry: python custom-hooks/custom_check.py
        language: system
        types: [python]
        pass_filenames: true
        exclude: ^custom-hooks/custom_check\.py$
        args: [--exclude=custom-hooks/custom_check.py,tests/*,docs/*]
