repos:
  - repo: local
    hooks:
      - id: custom-check
        name: custom check
        entry: python custom-hooks/custom_check.py
        language: system
        types: [python]
        files: src/
